name: Build

permissions:
  contents: write
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup tools from APT
        run: |
          sudo apt update
          sudo apt install -y \
            musl \
            llvm \
            clang

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl

      - name: Install Rust dependencies
        run: cargo fetch

      - name: Build Linux x64 musl
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          path: target/x86_64-unknown-linux-musl/release/wine-breeze

      - name: Create a new release
        if: ${{ github.event_name == 'push' }}
        run: |
          gh release create \
            ${{ github.ref_name }} \
            target/x86_64-unknown-linux-musl/release/wine-breeze \
            --title "Release ${{ github.ref_name }}"
